### ISSUE TITLE
machine_info.pyの出力について

### ISSUE THREAD

**Issue by kekke-gk** [project-hatohol/test-environment-manager#26]
$ sudo python3 machine_info.py
の出力について、以下のようにGroupとIPが割り振られていませんが、
正しい出力なのでしょうか？

\-----------------------------------------------------------------
No |Group| Name         | HostName     | IP           | State   |
\-----------------------------------------------------------------
 1 | N/A | env_base     | env_base     | not defined  | STOPPED | 
 2 | N/A | env_fluentd  | env_fluentd  | not defined  | STOPPED | 
 3 | N/A | env_hatohol_build | env_hatohol_build | not defined  | STOPPED | 
 4 | N/A | env_hatohol_rpm | env_hatohol_rpm | not defined  | STOPPED | 
 5 | N/A | env_nagios_nrpe | env_nagios_nrpe | not defined  | STOPPED | 
 6 | N/A | env_nagios_server3 | env_nagios_server3 | not defined  | STOPPED | 
 7 | N/A | env_nagios_server4 | env_nagios_server4 | not defined  | STOPPED | 
 8 | N/A | env_redmine  | env_redmine  | not defined  | STOPPED | 
 9 | N/A | env_zabbix_agent20 | env_zabbix_agent20 | not defined  | STOPPED | 
10 | N/A | env_zabbix_agent22 | env_zabbix_agent22 | not defined  | STOPPED | 
11 | N/A | env_zabbix_server20 | env_zabbix_server20 | not defined  | STOPPED | 
12 | N/A | env_zabbix_server22 | env_zabbix_server22 | not defined  | STOPPED |

**Comment by Mnakagawa** [comment]
はい。正しいです。
env_xxxxxとなっているコンテナは、のちにユーザーが作成するコンテナのベースとなるコンテナです。
GroupとIP Addressには、ユーザーがコンテナ作成の際にymlファイルで定義したものが挿入されます。

**Comment by kekke-gk** [comment]
ありがとうございます。
