### ISSUE TITLE
Appendix, Unit testの実行結果について

### ISSUE THREAD

**Issue by yyamma** [project-hatohol/test-environment-manager#27]
4.Noteの項目のHow to testで、$ python3 -m pytest test_machine_info.pyと$ python3 -m pytest test_machine_switcher.pyを実行した結果、どちらともエラー(failed)となって赤い枠線のものがでてしまいました。

**Comment by Mnakagawa** [comment]
申し訳ないです。
作成したテストが間違っていました。
修正してマージしましたので，手元にあるソースコードをアップデートしてから，
再度テストを行っていただけないでしょうか。

**Comment by yyamma** [comment]
ありがとうございます。
